security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            # anonymous: true
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: home
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800
                path: /
                domain: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/new-post, roles: ROLE_USER }
        - { path: ^/account, roles: ROLE_USER }

    role_hierarchy:
            ROLE_ADMIN: [ROLE_MANAGE_GENUS, ROLE_ALLOWED_TO_SWITCH]