controllers:
    resource: ../../src/Controller/
    type: annotation

# chat domain
controllers_chat:
    resource: ../../src/Chat/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
